pipeline {
    agent any
    stages {
        stage('build') {
            step {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            step {
                echo 'Running Unit Tests on worker app'
            }
        }
        stage('package') {
            step {
                echo 'Packaging worker app'
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for worker app is complited'
        }
    }
}
